name: flutter_page_indicators
description: Page indicator for flutter, with multiple build-in layouts.
version: 0.0.1
author: JZoom <jzoom8112@gmail.com>, JarvanMo <jarvan.mo@gmail.com>
homepage: https://github.com/OpenFlutter/flutter_page_indicator

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=0.1.4 <3.0.0"


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
